import psycopg2

uri = "postgres://avnadmin:AVNS_OUc5zfIntdvt3h9PwNg@pg-33128f75-coherentdrive-26b9.l.aivencloud.com:11299/defaultdb?sslmode=require"
conn = psycopg2.connect(uri)
cur = conn.cursor()

project_id = 1

tasks = [
    (1,  "Revised logo",                                                        "Adjust the logo mobile plus web",                                                                                                                                                                                              "Resolved"),
    (2,  "Credit shows 500 for users, made it 1000 and now 0",                  "",                                                                                                                                                                                                                             "Resolved"),
    (3,  "After signup it was not asking to complete the profile",               "",                                                                                                                                                                                                                             "Resolved"),
    (4,  "Footer address is cluttered and number should be one",                 "",                                                                                                                                                                                                                             "Resolved"),
    (5,  "After signup its not routing to the home page",                        "",                                                                                                                                                                                                                             "Resolved"),
    (6,  "The footer shows LinkedIn, so add it",                                 "",                                                                                                                                                                                                                             "Partial"),
    (7,  "Add one more email as subscription enquiry",                           "inquiry@nutraiqx.ai",                                                                                                                                                                                                         "Resolved"),
    (8,  "Add support email id as well in the support section",                  "",                                                                                                                                                                                                                             "Resolved"),
    (9,  "All the details in the company profile should be called once",         "We will work to optimize it",                                                                                                                                                                                                  "Partial"),
    (10, "Competitive intelligence is taking more time",                         "",                                                                                                                                                                                                                             "Partial"),
    (11, "White paper does not include all the details",                         "Dynamic the value of dollars $\nImpact Analysis of Key Factors\n-all the sources are mentioned below.\nremove the notes from the graphs of white papers\n- Product Form Coverage(dynamic)\n-graph would be below the particular segment\n-graph would contain year(2025)\n- Segment Distribution by Protein Source,2025\n- Regional Market Distribution,2025\n-same query should not deduct the credit multiple times", "Resolved"),
    (12, "Trade data import/export is not working",                              "-selection of multiple countries\n-credits should not get cut when the data is not visible\n- Please select 8 digit HS code for knowing volume (units)\n-realign the column name\n- Qty FY 2022-23* remove this column\n-multiple selection of the financial year and also data should show year based on the selection\n-remove this export csv features for free credits", "Resolved"),
    (13, "Units are missing in the trade data",                                  "",                                                                                                                                                                                                                             "Resolved"),
    (14, "Sources of all white papers are same",                                 "",                                                                                                                                                                                                                             "Resolved"),
    (15, "Query optimization - stepwise approach for accurate results",          "-Raw material, machinery, finished goods, trader\n-search query in the third step i.e 1 product name 2. Definition of product 3. Entity types",                                                                               "Pending"),
    (16, "Looking for partner should include all the entity types",              "Supplier, traders at last.\n-finished products (brands)",                                                                                                                                                                      "Resolved"),
    (17, "Footer should include all addresses, phone numbers, and email addresses", "",                                                                                                                                                                                                                         "Resolved"),
    (18, "Heading based on the filter selection of import/export data",          "",                                                                                                                                                                                                                             "Pending"),
    (19, "Quantity unit (kgs) should be after the value itself",                 "",                                                                                                                                                                                                                             "Resolved"),
    (20, "Asterisk suggestion: Please select 8-digit HS code...",                "",                                                                                                                                                                                                                             "Resolved"),
    (21, "Revenue range filter in the listing page",                             "",                                                                                                                                                                                                                             "Resolved"),
    (22, "Exact years should be mentioned on the column name of import/export",  "",                                                                                                                                                                                                                             "Resolved"),
    (23, "Giving the user ability to upload quotation",                          "",                                                                                                                                                                                                                             "Partial"),
    (24, "New updated logo for both light and dark mode",                        "",                                                                                                                                                                                                                             "Resolved"),
    (25, "Remove market analysis report",                                        "",                                                                                                                                                                                                                             "Resolved"),
    (26, "Remove view full report",                                              "",                                                                                                                                                                                                                             "Resolved"),
    (27, "Resolve the explanation of application",                               "",                                                                                                                                                                                                                             "Resolved"),
    (28, "Resolve the explanation of product type",                              "",                                                                                                                                                                                                                             "Resolved"),
    (29, "Rewrite the overview in the white paper",                              "",                                                                                                                                                                                                                             "Resolved"),
    (30, "Add definition at the top of the white paper",                         "",                                                                                                                                                                                                                             "Resolved"),
    (31, "Footer structure should be better",                                    "",                                                                                                                                                                                                                             "Resolved"),
    (32, "Make the submit request button functional",                            "Custom insight, contact us\n-subject based on them tags",                                                                                                                                                                      "Pending"),
    (33, "Remove the consumer facing brand",                                     "",                                                                                                                                                                                                                             "Resolved"),
    (34, "Modification in competitive intelligence report: Reliability score",   "",                                                                                                                                                                                                                             "Resolved"),
    (35, "Competitive Intelligence: Reliability and trust analysis paragraph",   "Heading with all the parameters in the bullet points.\nreviews and ratings",                                                                                                                                                  "Pending"),
    (36, "Competitive Intelligence: Graph should be single bar",                 "",                                                                                                                                                                                                                             "Resolved"),
    (37, "Competitive Intelligence: graph should be placed at bottom of the report", "",                                                                                                                                                                                                                        "Resolved"),
    (38, "Notes on every graph in very small text",                              "*Note: The derived data is based on publically available data and primary research responses from the end users.\nit should be on the left side of the graph",                                                                 "Pending"),
    (39, "News should be properly categorized",                                  "Reduce the bifurcation of the news",                                                                                                                                                                                           "Pending"),
    (40, "News should be relevant to the user",                                  "",                                                                                                                                                                                                                             "Resolved"),
    (41, "Entire card should be able to open the summary",                       "",                                                                                                                                                                                                                             "Resolved"),
    (42, "Redesign the entire database with proper segregation",                 "Now differentiation",                                                                                                                                                                                                          "Resolved"),
    (43, "Reroute the entire website based on the new database",                 "",                                                                                                                                                                                                                             "Pending"),
    (44, "Restructure the entire backend",                                       "",                                                                                                                                                                                                                             "Pending"),
    (45, "P and S should be capital in Protein Source",                          "",                                                                                                                                                                                                                             "Resolved"),
    (46, "Add company name in the form and rearrange the form",                  "Add contact us option in the footer, link it to contact us page. Similar to the enquiry form.\nLead shared to user would be shared to inquiry@nutraiqx\ntest-email\nsubject-Enquiry Lead for NutraIQX",                       "Partial"),
]

cur.execute("DELETE FROM tasks WHERE project_id = %s", (project_id,))

rows = [(project_id, t[0], t[1], t[2], t[3]) for t in tasks]
cur.executemany(
    "INSERT INTO tasks (project_id, sno, task, comments, status) VALUES (%s, %s, %s, %s, %s)",
    rows,
)
conn.commit()

cur.execute("SELECT COUNT(*) FROM tasks WHERE project_id = %s", (project_id,))
print(f"Inserted {cur.fetchone()[0]} tasks into 'wednesday client'.")
cur.close()
conn.close()
